services:
  - docker

script:
  - docker-compose build
  - docker-compose run web yarn install --check-files
  - docker-compose run web rails db:create db:migrate
  - docker-compose run web rails test