language: minimal

services:
  - docker

before_install:
  - docker-compose build

install:
  # - docker-compose run web yarn install --check-files
  - docker-compose run web rails db:create db:migrate

script:
  - docker-compose run web rails test